# Generated by Django 5.2.8 on 2025-11-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_skill_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='category',
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='categories',
            field=models.ManyToManyField(related_name='providers', to='providers.category'),
        ),
    ]
